### PR TITLE
e.getPullRequest().getTitle(this);

### PR DESCRIPTION
**Pull request by Computerfile**
Added a command in order to allow the user to sell all of their stocks of a certain company. This file can be found under the "cmd/ancap" folder of the project. used the "send" function instead of the static app.embed.

### CODE REVIEW

**Comment by AstolfoDev** [comment]
Was this code tested? If so, could we see screenshots of this code being ran and working?

**Comment by Computerfile** [comment]
yeah, working fine, as you can see.

Capture

**Comment by Znunu** [comment]
Every command remixed together? What do you say @AstolfoDev, do we help this man get his shirt?

**Comment by AstolfoDev** [comment]
Hell fuckin' yeah, let's do this! >:D

**Pull request merged**
